export interface SlotConfig {
  isFront: boolean;
  name: string;
  slotName: string;
  sn: string;
  version: string;
  limitImageWidth: number;
  limitImageHeight: number;
  top: number; // avatar slot position: top
  left: number; // avatar slot position: left
  imageBlob?: Blob;
  emptyOverride?: boolean | null;
  removeBase?: boolean | null;
  isHidden?: boolean;
}

export const SlotConfigs: SlotConfig[] = [
  {
    isFront: true,
    slotName: 'head_face_3',
    sn: 'LOCALSN',
    name: 'Head Face',
    version: '0',
    limitImageWidth: 85,
    limitImageHeight: 93,
    top: 7,
    left: 90,
    emptyOverride: null,
  },
  {
    isFront: true,
    slotName: 'head_base_3',
    sn: 'LOCALSN',
    name: 'Head Base',
    version: '0',
    limitImageWidth: 85,
    limitImageHeight: 93,
    top: 7,
    left: 253,
    emptyOverride: null,
  },
  {
    isFront: true,
    slotName: 'head_mask_3',
    sn: 'LOCALSN',
    name: 'Head Mask',
    version: '0',
    limitImageWidth: 85,
    limitImageHeight: 93,
    top: 7,
    left: 413,
    emptyOverride: null,
  },
  {
    isFront: true,
    slotName: 'barm_cost_3',
    sn: 'LOCALSN',
    name: 'Right Arm',
    version: '0',
    limitImageWidth: 21,
    limitImageHeight: 26,
    top: 150,
    left: 136,
    emptyOverride: null,
    removeBase: null,
  },
  {
    isFront: true,
    slotName: 'barm_base_3',
    sn: 'LOCALSN',
    name: 'Right Arm Base',
    version: '0',
    limitImageWidth: 21,
    limitImageHeight: 26,
    top: 260,
    left: 136,
    emptyOverride: null,
    removeBase: null,
    isHidden: true,
  },
  {
    isFront: true,
    slotName: 'body_cost_3',
    sn: 'LOCALSN',
    name: 'Body Cost',
    version: '0',
    limitImageWidth: 44,
    limitImageHeight: 36,
    top: 177,
    left: 254,
    emptyOverride: null,
    removeBase: null,
  },
  {
    isFront: true,
    slotName: 'body_base_3',
    sn: 'LOCALSN',
    name: 'Body Base',
    version: '0',
    limitImageWidth: 44,
    limitImageHeight: 36,
    top: 67,
    left: 254,
    emptyOverride: null,
    removeBase: null,
    isHidden: true,
  },
  {
    isFront: true,
    slotName: 'body_cost_dres_3',
    sn: 'LOCALSN',
    name: 'Body Dress',
    version: '0',
    limitImageWidth: 44,
    limitImageHeight: 36,
    top: 295,
    left: 254,
    emptyOverride: null,
  },
  {
    isFront: true,
    slotName: 'farm_cost_3',
    sn: 'LOCALSN',
    name: 'Left Arm',
    version: '0',
    limitImageWidth: 21,
    limitImageHeight: 26,
    top: 150,
    left: 377,
    emptyOverride: null,
    removeBase: null,
  },
  {
    isFront: true,
    slotName: 'farm_base_3',
    sn: 'LOCALSN',
    name: 'Left Arm Base',
    version: '0',
    limitImageWidth: 21,
    limitImageHeight: 26,
    top: 260,
    left: 377,
    emptyOverride: null,
    removeBase: null,
    isHidden: true,
  },
  {
    isFront: true,
    slotName: 'barm_weap_3',
    sn: 'LOCALSN',
    name: 'Right Arm Weapon',
    version: '0',
    limitImageWidth: 21,
    limitImageHeight: 26,
    top: 176,
    left: 19,
    emptyOverride: null,
  },
  {
    isFront: true,
    slotName: 'barm_shld_3',
    sn: 'LOCALSN',
    name: 'Right Arm Handheld',
    version: '0',
    limitImageWidth: 21,
    limitImageHeight: 26,
    top: 286,
    left: 19,
    emptyOverride: null,
  },
  {
    isFront: true,
    slotName: 'farm_weap_3',
    sn: 'LOCALSN',
    name: 'Left Arm Weapon',
    version: '0',
    limitImageWidth: 21,
    limitImageHeight: 26,
    top: 176,
    left: 495,
    emptyOverride: null,
  },
  {
    isFront: true,
    slotName: 'farm_shld_3',
    sn: 'LOCALSN',
    name: 'Left Arm Handheld',
    version: '0',
    limitImageWidth: 21,
    limitImageHeight: 26,
    top: 286,
    left: 495,
    emptyOverride: null,
  },
  {
    isFront: true,
    slotName: 'bleg_cost_3',
    sn: 'LOCALSN',
    name: 'Right Leg',
    version: '0',
    limitImageWidth: 17,
    limitImageHeight: 25,
    top: 450,
    left: 186,
    emptyOverride: null,
    removeBase: null,
  },
  {
    isFront: true,
    slotName: 'bleg_base_3',
    sn: 'LOCALSN',
    name: 'Right Leg Base',
    version: '0',
    limitImageWidth: 17,
    limitImageHeight: 25,
    top: 450,
    left: 76,
    emptyOverride: null,
    removeBase: null,
    isHidden: true,
  },
  {
    isFront: true,
    slotName: 'fleg_cost_3',
    sn: 'LOCALSN',
    name: 'Left Leg',
    version: '0',
    limitImageWidth: 17,
    limitImageHeight: 25,
    top: 450,
    left: 321,
    emptyOverride: null,
    removeBase: null,
  },
  {
    isFront: true,
    slotName: 'fleg_base_3',
    sn: 'LOCALSN',
    name: 'Left Leg Base',
    version: '0',
    limitImageWidth: 17,
    limitImageHeight: 25,
    top: 450,
    left: 431,
    emptyOverride: null,
    removeBase: null,
    isHidden: true,
  },
  {
    isFront: false,
    slotName: 'head_base_1',
    sn: 'LOCALSN',
    name: 'Head Base',
    version: '0',
    limitImageWidth: 85,
    limitImageHeight: 93,
    top: 7,
    left: 253,
    emptyOverride: null,
  },
  {
    isFront: false,
    slotName: 'head_mask_1',
    sn: 'LOCALSN',
    name: 'Head Mask',
    version: '0',
    limitImageWidth: 85,
    limitImageHeight: 93,
    top: 7,
    left: 413,
    emptyOverride: null,
  },
  {
    isFront: false,
    slotName: 'farm_cost_1',
    sn: 'LOCALSN',
    name: 'Left Arm',
    version: '0',
    limitImageWidth: 21,
    limitImageHeight: 26,
    top: 150,
    left: 136,
    emptyOverride: null,
    removeBase: null,
  },
  {
    isFront: false,
    slotName: 'farm_base_1',
    sn: 'LOCALSN',
    name: 'Left Arm Base',
    version: '0',
    limitImageWidth: 21,
    limitImageHeight: 26,
    top: 260,
    left: 136,
    emptyOverride: null,
    removeBase: null,
    isHidden: true,
  },
  {
    isFront: false,
    slotName: 'body_cost_1',
    sn: 'LOCALSN',
    name: 'Body Cost',
    version: '0',
    limitImageWidth: 44,
    limitImageHeight: 36,
    top: 177,
    left: 254,
    emptyOverride: null,
    removeBase: null,
  },
  {
    isFront: false,
    slotName: 'body_base_1',
    sn: 'LOCALSN',
    name: 'Body Base',
    version: '0',
    limitImageWidth: 44,
    limitImageHeight: 36,
    top: 67,
    left: 254,
    emptyOverride: null,
    removeBase: null,
    isHidden: true,
  },
  {
    isFront: false,
    slotName: 'body_cost_dres_1',
    sn: 'LOCALSN',
    name: 'Body Dress',
    version: '0',
    limitImageWidth: 44,
    limitImageHeight: 36,
    top: 295,
    left: 254,
    emptyOverride: null,
  },
  {
    isFront: false,
    slotName: 'barm_cost_1',
    sn: 'LOCALSN',
    name: 'Right Arm',
    version: '0',
    limitImageWidth: 21,
    limitImageHeight: 26,
    top: 150,
    left: 377,
    emptyOverride: null,
    removeBase: null,
  },
  {
    isFront: false,
    slotName: 'barm_base_1',
    sn: 'LOCALSN',
    name: 'Right Arm Base',
    version: '0',
    limitImageWidth: 21,
    limitImageHeight: 26,
    top: 260,
    left: 377,
    emptyOverride: null,
    removeBase: null,
    isHidden: true,
  },
  {
    isFront: false,
    slotName: 'farm_weap_1',
    sn: 'LOCALSN',
    name: 'Left Arm Weapon',
    version: '0',
    limitImageWidth: 21,
    limitImageHeight: 26,
    top: 176,
    left: 19,
    emptyOverride: null,
  },
  {
    isFront: false,
    slotName: 'farm_shld_1',
    sn: 'LOCALSN',
    name: 'Left Arm Handheld',
    version: '0',
    limitImageWidth: 21,
    limitImageHeight: 26,
    top: 286,
    left: 19,
    emptyOverride: null,
  },
  {
    isFront: false,
    slotName: 'barm_weap_1',
    sn: 'LOCALSN',
    name: 'Right Arm Weap',
    version: '0',
    limitImageWidth: 21,
    limitImageHeight: 26,
    top: 176,
    left: 495,
    emptyOverride: null,
  },
  {
    isFront: false,
    slotName: 'barm_shld_1',
    sn: 'LOCALSN',
    name: 'Right Arm Handheld',
    version: '0',
    limitImageWidth: 21,
    limitImageHeight: 26,
    top: 286,
    left: 495,
    emptyOverride: null,
  },
  {
    isFront: false,
    slotName: 'fleg_cost_1',
    sn: 'LOCALSN',
    name: 'Left Leg',
    version: '0',
    limitImageWidth: 17,
    limitImageHeight: 25,
    top: 450,
    left: 186,
    emptyOverride: null,
    removeBase: null,
  },
  {
    isFront: false,
    slotName: 'fleg_base_1',
    sn: 'LOCALSN',
    name: 'Left Leg Base',
    version: '0',
    limitImageWidth: 17,
    limitImageHeight: 25,
    top: 450,
    left: 76,
    emptyOverride: null,
    removeBase: null,
    isHidden: true,
  },
  {
    isFront: false,
    slotName: 'bleg_cost_1',
    sn: 'LOCALSN',
    name: 'Right Leg',
    version: '0',
    limitImageWidth: 17,
    limitImageHeight: 25,
    top: 450,
    left: 321,
    emptyOverride: null,
    removeBase: null,
  },
  {
    isFront: false,
    slotName: 'bleg_base_1',
    sn: 'LOCALSN',
    name: 'Right Leg Base',
    version: '0',
    limitImageWidth: 17,
    limitImageHeight: 25,
    top: 450,
    left: 431,
    emptyOverride: null,
    removeBase: null,
    isHidden: true,
  },
];
